### ISSUE TITLE
?player

### ISSUE THREAD

**Issue by ghost** [Muqsit/2FA#1]
https://github.com/Muqsit/2FA/blob/master/src/muqsit/tfa/player/TFAPlayer.php
Line 103

**Comment by Muqsit** [comment]
Hm, what's wrong here?

**Comment by ghost** [comment]
if ?player should be a variable it should not start with $

**Comment by Muqsit** [comment]
It's not an issue, it's PHP7.1's nullable types.

**Comment by ghost** [comment]
OK thank for the info

**Comment by Muqsit** [comment]
👍
